title: "Help Center"
description: "Product Support & Knowledge Base"
baseurl: ""
url: "https:pranayb23.github.io/github_pages"

remote_theme: just-the-docs/just-the-docs

search_enabled: true
aux_links:
  "Contact Support":
    - "https://your-support-url"
footer_content: "Â© {{ site.time | date: '%Y' }} Your Company"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  categories:
    output: true
    permalink: /:collection/:name/
  articles:
    output: true
    permalink: /:collection/:name/
